apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: agritwin-api-tls
  namespace: at-paddock
spec:
  secretName: agritwin-api-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - api.agritwin.ai
  - webapp.agritwin.ai